/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zkjinshi_jni_aes_AESManager */

#ifndef _Included_com_zkjinshi_jni_aes_AESManager
#define _Included_com_zkjinshi_jni_aes_AESManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zkjinshi_jni_aes_AESManager
 * Method:    getEncryptKey
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zkjinshi_jni_aes_AESManager_getEncryptKey
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
